feature_extract_enable : 1
point_filter_num : 2
max_iteration : 6
dense_map_enable : 1
filter_size_surf : 0.15
filter_size_map : 0.3
cube_side_length : 20
grid_size : 40
patch_size : 8
img_enable : 0
lidar_enable : 1
outlier_threshold : 300 # 78 100 156
ncc_en: false
ncc_thre: 0
img_point_cov : 100 # 1000
laser_point_cov : 0.001 # 0.001
pose_output_en: false
delta_time: 0.0

common:
    lid_topic:  "/livox/lidar"
    imu_topic:  "/livox/imu"

preprocess:
    lidar_type: 1 # 1:Livox LiDAR  2:VELO16  3:OUST64  4:XT32  5:Mid360
    scan_line: 4 # 16  64  32
    blind: 0.1 # blind x m disable

mapping:
    acc_cov_scale: 100
    gyr_cov_scale: 10000
    extrinsic_T: [ -0.011, -0.02329, 0.04412 ] # horizon 0.05512, 0.02226, -0.0297 # mid360 -0.011, -0.02329, 0.04412 # avia 0.04165, 0.02326, -0.0284 
    extrinsic_R: [ 1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]

pcd_save:
    pcd_save_en: true

camera:
    img_topic: /cam0

    Rcl: [0.00317983, -0.999907, 0.0132752, 
      -0.0151056, -0.0133218, -0.999797, 
       0.999881, 0.00297865, -0.0151466]
    Pcl: [-0.0309436, -0.0447041, -0.0838355]
















    
